  
spring:
  profiles:
    active:
    - dev
    
---
spring:
  profiles: dev 
  application:
    name: dev
        
---
spring:
   profiles: test 
   application:
    name: test
# 项目相关配置
system:
  # 名称
  name: system
  # 版本
  version: 2.4.0
  # 版权年份
  copyrightYear: 2018
  # 文件上传路径
  profile: D:/profile/
  # 获取ip地址开关
  addressEnabled: false