spring:
  application:
    name: ysb-zuul
  profiles: zuul
eureka:
  client:
    service-url:
      #defaultZone: http://192.168.203.38:8762/eureka/
      #defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://eureka2:8761/eureka/,http://eureka1:8761/eureka/
      defaultZone: http://192.168.102.81:8761/eureka/,http://192.168.102.83:8761/eureka/,http://192.168.102.84:8761/eureka/
  instance:
    #instance-id: injob对外服务接口-8003,https8002  # 人性化显示出服务的信息
    prefer-ip-address: true
server:
  port: 6872

ribbon:
  eureka:
    enabled: false
  ReadTimeout: 600000
  ConnectTimeout: 600000 
  
zuul:
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000
  routes:
    eureka:
      path: /eureka/**
      custom-sensitive-headers: true
      sensitive-headers:
      #stripPrefix: false 
      url: http://localhost:8761/
    test:
      path: /test/**
      sensitive-headers:
      custom-sensitive-headers: true
      serviceId: test
      stripPrefix: true 
      #url: https://www.baidu.com/
      
    ysbmdm:
      path: /ysbmdm/**
      sensitive-headers:
      custom-sensitive-headers: true
      stripPrefix: false 
      serviceId: ysbmdm

    wxmd:
      path: /wxmd/**
      sensitive-headers:
      custom-sensitive-headers: true
      stripPrefix: false 
      serviceId: wxmd

    
ysbmdm:
  ribbon:
    listOfServers: 192.168.102.83:8772,192.168.102.84:8772
wxmd:
  ribbon:
    listOfServers: 192.168.102.81:8772 
test:
  ribbon:
    listOfServers: www.atguigu.com,www.slimego.cn
 

    
https:
  port: 7702
  ssl:
    key-store: classpath:keystore.jks
    #key-store-password: 123456
    #key-password: 123456
    key-store-password: 84443596086
    key-password: 84443596086 
    
---
spring:
  application:
    name: ysb-system
  profiles: system
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  redis:
  #hostName: 47.106.166.51
    #hostName: r-vm64d2f02ddb1b04.redis.rds.ops.yzcloud.cn
    #hostName: 39.106.171.148
    #hostName: 192.168.201.36
    #hostName: localhost
    hostName: 192.168.102.80
    port: 6379
    #auth: 1Qazxsw2
    auth: 123456
    max_active: 1024
    max_idle: 200
    max_wait: 10000
    timeout: 10000
    test_on_borrow: true
  rabbitmq:
    #host: 192.168.201.36
    #host: 39.106.171.148
    #host: localhost
    #host: 47.106.166.51
    host: 192.168.102.80
    port: 5672
    #username: admin
    #password: ysbrabbitmq
    username: xiao
    password: xiao


# 项目相关配置
system:
  # 名称
  name: system
  # 版本
  version: 2.4.0
  # 版权年份
  copyrightYear: 2018
  # 文件上传路径
  profile: D:/profile/
  # 获取ip地址开关
  addressEnabled: false
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://192.168.201.22:8771/eureka/
      #http://10.4.129.45:8761/eureka/
      #http://eureka:8761/eureka/
      #defaultZone: http://192.168.102.81:8761/eureka/
      defaultZone: http://192.168.102.83:8761/eureka/
  instance:
       #instance-id: system 微服务id名
       prefer-ip-address: true 
# 开发环境配置
server:
  # 服务端口
  port: 8772
  
  servlet:
    # 项目contextPath
    context-path: /tx
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
  #ssl:
  #  key-store: classpath:keystore.jks
  #  key-store-password: 123456
  #  key-password: 123456
zuul:
  routes:
    delivery:
      path: /delivery/**
      serviceId: ysb-eoms-delivery
      sensitive-headers: 
      custom-sensitive-headers: true
    settings:
      path: /settings/**
      serviceId: ysb-eoms-settings
      sensitive-headers: 
      custom-sensitive-headers: true
    account:
      path: /account/**
      serviceId: ysb-eoms-account
      sensitive-headers: 
      custom-sensitive-headers: true
    search:
      path: /search/**
      serviceId: ysb-eoms-search
      sensitive-headers: 
      custom-sensitive-headers: true
      
#Ribbon的超时时间全局设置
ribbon:
    ReadTimeout: 600000
    ConnectTimeout: 600000 
# 日志配置
logging:
  level:
    com.ysb.system: info
    org.springframework: WARN
    org.spring.springboot.dao: info

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置


# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ysb.system.project
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen: 
  # 作者
  author: ysb
  # 默认生成包路径 module 需改成自己的模块名称 如 system monitor tool
  packageName: com.ysb.system.project.module
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀(类名不会包含表前缀)
  tablePrefix: sys_

#http:
#  port: 8080
https:
  port: 8778
  ssl:
    key-store: classpath:keystore.jks
    #key-store-password: 123456
    #key-password: 123456
    key-store-password: 84443596086
    key-password: 84443596086  
    #key-store: classpath:2716019_www.ysbwms.xyz.pfx
    #key-store-password: f7625Y0B
    #key-password: f7625Y0B
    
    
    
    
qimen: 
  #云仓UAT
  cwmUrl: http://211.156.195.123/jdpt-cwmin-job/
  #云仓生产
  #cwmUrl: http://211.156.195.122/jdpt-cwmin-job/
  #奇门沙箱
  qimenUrl: http://qimenapi.tbsandbox.com/router/qimen
  #菜鸟正式环境 无测试环境
  cainiaoUrl: http://gw.api.taobao.com/router/rest
  sessionKey: 61027174b863dd978e23bda5413c04b409785e39426d6812185266464
  #奇门正式环境
  #qimenUrl: http://qimen.api.taobao.com/router/qimen/service
  
  #测试沙箱环境
  appKey: 1025071756
  #正式环境
  #appKey: 25071756
 
  format: xml
  v : 2.0
  #自测沙箱环境
  customerId: c1537500075110
  #ERP联测
  #customerId: c1544408141756
  #正式生产
  #customerId: cewms2019010401
  signMethod: md5
  
  
  
  #自测沙箱/ERP联测
  appSecret: sandbox9f41e4fe4bef914bb28be3de6
   
  #正式
  #app_secret: 8fec11f9f41e4fe4bef914bb28be3de6
  
  #沙箱环境
  toQimenAppKey: 1012405954
  toQimenCustomerId: c1544408141756
  toQimenAppSecret: sandbox9f41e4fe4bef914bb28be3de6s 
    