  
spring:
  profiles:
    active:
    - dev
    
---
server:
  port: 8201

spring:
  profiles: dev 
  application:
    name: dev1
eureka:
  client:
    service-url:
      defaultZone: http://192.168.102.83:8761/eureka/       
---
server:
  port: 8202

spring:
   profiles: test 
   application:
    name: dev1
eureka:
  client:
    service-url:
      defaultZone: http://192.168.102.83:8761/eureka/